### ISSUE TITLE
Bug in sample code

### ISSUE THREAD

**Issue by gvanwaelvelde** [s-aska/p5-WebService-Dropbox#16]
Hello,

I love your WebService::Dropbox, however there's a small bug in your sample code:
The $box variable should be $dropbox.

Kind regards,

**Comment by s-aska** [comment]
@gvanwaelvelde 
I succeeded in facing and correcting a long-standing problem.
https://github.com/s-aska/p5-WebService-Dropbox/commit/a418e25fa3a77ea4bb339b482013c5bf35a0802b#
